name: Build and Publish to Github packages

# Controls when the action will run. Triggers the workflow on push request
on:
  push:
    paths:
    - '.github/workflows/**'
    - 'docker/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Login to Docker Hub
    - name: Login to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin

    # Build and publish Docker image
    - name: Docker build and push
      run: docker build -f ${GITHUB_WORKSPACE}/docker/Dockerfile -t ghcr.io/${{ github.actor }}/azure-coredns:latest . && docker push ghcr.io/${{ github.actor }}/azure-coredns:latest
      working-directory: docker
      env:
        IMAGE_NAME: azure-coredns
