name: Build and Publish to Github packages

on:
  push:
    paths:
    - '.github/workflows/**'
    - 'docker/**'
env:
  REGISTRY: ghcr.io
  IMAGE: azure-coredns:latest
  
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

    - uses: actions/checkout@v2

    - name: Login to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin

    - name: Build and push image
      run: cd docker; docker build -t $REGISTRY/${{ github.actor }}/$IMAGE . && docker push $REGISTRY/${{ github.actor }}/$IMAGE

